#path_vectors: ./../../../test/data/embeddings/npy/

path_vectors: /usr/cs/grad/master/svenkatr/Desktop/SequenceLabelling_NLP_Tasks/data/glove-emb/300d
path_dataset: /usr/cs/grad/master/svenkatr/Desktop/SequenceLabelling_NLP_Tasks/data
window: 4
task: pos
